packages:
  - packages/*
  - packages/@core/*
  - packages/@core/ui-kit/*
  - internal/*
  - internal/lint-config/*
  - apps/*

catalog:
  '@eslint/js': ^9.36.0
  '@types/node': ^24.5.2
  eslint: ^9.36.0
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: 2.5.6
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-unused-imports: ^4.2.0
  globals: ^16.4.0
  husky: 9.1.7
  prettier: 3.6.2
  turbo: 2.5.6
  typescript: ^5.9.2
  typescript-eslint: ^8.44.0
  unbuild: ^3.6.1

catalogMode: strict
