packages:
  - packages/*
  - packages/@core/*
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/effects/*
  - internal/*
  - internal/lint-config/*
  - scripts/*
  - apps/*

catalog:
  '@changesets/git': ^3.0.4
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@csstools/postcss-oklab-function': ^4.0.12
  '@ctrl/tinycolor': ^4.2.0
  '@eslint/js': ^9.36.0
  '@hookform/resolvers': ^5.2.2
  '@iconify/json': ^2.2.388
  '@iconify/react': ^6.0.2
  '@iconify/tailwind': ^1.2.0
  '@iconify/tailwind4': ^1.0.6
  '@jspm/generator': ^2.7.0
  '@manypkg/get-packages': 3.1.0
  '@pnpm/workspace.read-manifest': ^1000.2.4
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-aspect-ratio': ^1.1.7
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-menubar': ^1.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.7
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toggle': 1.1.10
  '@radix-ui/react-toggle-group': ^1.1.11
  '@radix-ui/react-tooltip': ^1.2.8
  '@reactuses/core': 6.1.0
  '@stylistic/stylelint-plugin': ^4.0.0
  '@tailwindcss/postcss': ^4.1.14
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.1.14
  '@tanstack/react-router': ^1.132.47
  '@tanstack/react-store': ^0.8.0
  '@tanstack/react-table': ^8.21.3
  '@types/archiver': ^6.0.3
  '@types/html-minifier-terser': ^7.0.2
  '@types/lodash': ^4.17.20
  '@types/node': ^24.5.2
  '@types/nprogress': ^0.2.3
  '@types/react': 19.1.15
  '@types/react-dom': 19.1.9
  '@types/react-transition-group': ^4.4.12
  '@types/sortablejs': ^1.15.8
  '@vitejs/plugin-react': ^5.0.3
  '@vitejs/plugin-react-swc': 4.1.0
  antd: ^5.27.4
  archiver: ^7.0.1
  autoprefixer: ^10.4.21
  cac: ^6.7.14
  chalk: ^5.6.2
  cheerio: ^1.1.2
  circular-dependency-scanner: ^2.3.0
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  commitlint-plugin-function-rules: ^4.0.2
  consola: ^3.4.2
  cross-env: ^10.1.0
  cspell: ^9.2.1
  cssnano: ^7.1.1
  cz-git: ^1.12.0
  czg: ^1.12.0
  date-fns: ^4.1.0
  dayjs: ^1.11.18
  defu: ^6.1.4
  depcheck: ^1.4.7
  dotenv: ^17.2.2
  embla-carousel-react: ^8.6.0
  eslint: ^9.36.0
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: 2.5.6
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-unused-imports: ^4.2.0
  execa: ^9.6.0
  find-up: ^8.0.0
  get-port: ^7.1.0
  globals: ^16.4.0
  happy-dom: ^19.0.2
  html-minifier-terser: ^7.2.0
  husky: 9.1.7
  input-otp: ^1.4.2
  lint-staged: ^16.2.0
  loadsh: ^0.0.4
  localforage: ^1.10.0
  lodash: ^4.17.21
  lucide-react: 0.545.0
  next-themes: ^0.4.6
  nitropack: ^2.12.6
  nprogress: ^0.2.0
  ora: ^9.0.0
  pkg-types: ^2.3.0
  postcss: 8.5.6
  postcss-html: ^1.8.0
  postcss-scss: ^4.0.9
  prettier: 3.6.2
  publint: 0.3.13
  radix-ui: ^1.4.3
  react: 19.1.1
  react-day-picker: ^9.11.1
  react-dom: 19.1.1
  react-hook-form: ^7.65.0
  react-resizable-panels: ^3.0.6
  react-router: ^7.9.3
  react-transition-group: ^4.4.5
  react-use: ^17.6.0
  recharts: ^3.3.0
  resolve.exports: ^2.0.3
  rimraf: 6.0.1
  rollup: ^4.52.3
  rollup-plugin-visualizer: ^6.0.3
  sass: ^1.93.2
  sonner: ^2.0.7
  sortablejs: ^1.15.6
  stylelint: ^16.24.0
  stylelint-config-recess-order: ^7.3.0
  stylelint-config-recommended: ^17.0.0
  stylelint-config-recommended-scss: ^16.0.1
  stylelint-config-standard: ^39.0.0
  stylelint-order: ^7.0.0
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^6.12.1
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.13
  tailwindcss-animate: ^1.0.7
  theme-colors: ^0.1.0
  tsdown: ^0.15.6
  turbo: 2.5.6
  typescript: ^5.9.2
  typescript-eslint: ^8.44.0
  unbuild: ^3.6.1
  vaul: ^1.1.2
  vite: 7.1.7
  vite-plugin-compression: ^0.5.1
  vite-plugin-compression2: ^2.2.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-pwa: ^1.0.3
  vite-plugin-react-click-to-component: ^4.0.0
  vitest: ^3.2.4
  watermark-js-plus: ^1.6.3
  zod: ^4.1.12
  zustand: ^5.0.8

catalogMode: strict
