packages:
  - packages/*
  - packages/@core/*
  - packages/@core/ui-kit/*
  - internal/*
  - internal/lint-config/*
  - scripts/*
  - apps/*

catalog:
  '@changesets/git': ^3.0.4
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@eslint/js': ^9.36.0
  '@manypkg/get-packages': ^3.1.0
  '@types/node': ^24.5.2
  cac: ^6.7.14
  chalk: ^5.6.2
  circular-dependency-scanner: ^2.3.0
  commitlint-plugin-function-rules: ^4.0.2
  consola: ^3.4.2
  cspell: ^9.2.1
  cz-git: ^1.12.0
  czg: ^1.12.0
  dayjs: ^1.11.18
  depcheck: ^1.4.7
  eslint: ^9.36.0
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: 2.5.6
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-unused-imports: ^4.2.0
  execa: ^9.6.0
  find-up: ^8.0.0
  globals: ^16.4.0
  husky: 9.1.7
  lint-staged: ^16.2.0
  ora: ^9.0.0
  pkg-types: ^2.3.0
  prettier: 3.6.2
  publint: 0.3.13
  rimraf: ^6.0.1
  turbo: 2.5.6
  typescript: ^5.9.2
  typescript-eslint: ^8.44.0
  unbuild: ^3.6.1

catalogMode: strict
